const pages=[
{id:'overview',icon:'⌂',label:'Portfolio Overview'},
{id:'questions',icon:'?',label:'Analytical Questions'},
{id:'qc',icon:'✓',label:'Validation & QC'},
{id:'pipeline',icon:'⇄',label:'Data Pipeline'},
{id:'sas-python',icon:'</>',label:'SAS → Python'},
{id:'analysis',icon:'∑',label:'Analysis & Results'},
{id:'visuals',icon:'▥',label:'Visualizations'},
{id:'deliverables',icon:'✓',label:'Project Deliverables'},
{id:'resume',icon:'★',label:'Resume Highlights'}];
const nav=document.getElementById('navigation'), main=document.getElementById('mainContent');
nav.innerHTML=pages.map((p,i)=>`<button class="nav-button ${i===0?'active':''}" data-page="${p.id}"><span class="nav-icon">${p.icon}</span><span>${p.label}</span></button>`).join('');
const metrics=`<div class="metrics-grid">
<div class="metric-card"><div class="metric-top"><span class="metric-label">STORM SUMMARY RECORDS</span><span class="metric-icon">#</span></div><div class="metric-value">3,172</div><div class="metric-note">Prepared records · limitations documented</div></div>
<div class="metric-card"><div class="metric-top"><span class="metric-label">DETAIL OBSERVATIONS</span><span class="metric-icon">≋</span></div><div class="metric-value">50,764</div><div class="metric-note">Detailed storm observations analyzed</div></div>
<div class="metric-card"><div class="metric-top"><span class="metric-label">2016 STORMS</span><span class="metric-icon">↗</span></div><div class="metric-value">90</div><div class="metric-note">Storm-level wind statistics produced</div></div>
<div class="metric-card"><div class="metric-top"><span class="metric-label">DAMAGE RECORDS</span><span class="metric-icon">$</span></div><div class="metric-value">38</div><div class="metric-note">Cost-linked storms in damage analysis</div></div></div>`;
const head=(eyebrow,title,desc,button='')=>`<div class="page-header"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${desc}</p></div>${button}</div>`;
const publication={github:'https://github.com/alphatraore/python-storm-data-analysis',demo:'https://alpha-traore-storm-analytics.alpha-traore8299.chatgpt.site'};
const publicationLinks=()=>`<section class="card" style="margin-bottom:20px"><h3>Explore the project</h3><div class="tech-pills">${publication.github?`<a class="button secondary" href="${publication.github}">GitHub repository</a>`:'<span class="pill">GitHub · URL not configured</span>'}${publication.demo?`<a class="button secondary" href="${publication.demo}">Live demo</a>`:'<span class="pill">Live demo · URL not configured</span>'}<a class="button secondary" href="python-storm-data-analysis-source.zip" download>Download source</a></div></section>`;
const views={
questions:()=>`${head('ANALYTICAL PURPOSE','Questions & Decision Context','Historical descriptive analysis for comparing storm activity, intensity, and reported damage.')}
<div class="section-grid"><section class="card"><h3>Where was activity concentrated?</h3><p>Compare 2016 storm counts by basin to guide geographic review. Counts describe the supplied dataset and are not population-adjusted risk estimates.</p><h3>Which storms had stronger observed winds?</h3><p>Compare mean, minimum, and maximum recorded wind by season, basin, and storm name within 2016. These summaries help identify records for deeper review; sampling frequency affects means.</p></section><section class="card"><h3>Which events carried the largest recorded costs?</h3><p>The damage table ranks Katrina ($161.3B), Harvey ($125B), and Maria ($90B) highest among the 38 linked records.</p><h3>How should results be used?</h3><p>Prioritize historical event review and communicate patterns. This project does not estimate future losses, establish causality, or normalize costs for inflation and exposure.</p></section></div>`,
qc:()=>`${head('VERIFIED ARTIFACT CHECKS','Validation & Quality Control','All 80 code cells executed successfully in sequence; independent checks verified regenerated outputs.','<a class="button" href="qc-results.json" download>Download QC evidence</a>')}
<div class="section-grid"><section class="card"><h3>Verified results</h3><ul><li>3,172 summary rows; 50,764 detailed observations.</li><li>All 90 exported season/basin/name wind summaries match independently recomputed 2016 means, minima, and maxima after rounding.</li><li>StormLength matches EndDate minus StartDate for all summary rows.</li><li>The two 38-row damage CSV exports agree and costs are sorted descending.</li><li>Excel report contains five expected analysis sheets.</li></ul><a href="validate_portfolio.py" download>Download reproducible validation script</a></section><section class="card"><h3>Identity safeguards & remaining limitations</h3><ul><li>Zero duplicate complete season/basin/name StormIDs.</li><li>70 ambiguous season/name candidates and 80 incomplete identities are excluded from damage-link eligibility and retained in audit CSVs.</li><li>All 38 input damage records match uniquely; the merge enforces many-to-one cardinality.</li><li>Wind grouping now separates basins: 90 summaries. Sixty detail observations with incomplete group identifiers are excluded and counted.</li><li>23 missing maximum-wind values are retained without imputation.</li></ul><p>Every code cell was rerun using a headless Python runner with a display shim; no Jupyter kernel was used. Detail Wind units still require source verification. MaxWindMPH is explicitly labeled. No values or ambiguous identities were guessed.</p></section></div>`,
overview:()=>`${head('PYTHON ANALYTICS PORTFOLIO','Storm Data Analysis Pipeline','A reproducible analytics project demonstrating practical Python, SAS data ingestion, data transformation, statistical summarization, visualization, and automated reporting.','<a class="button" href="python-storm-data-analysis-source.zip" download>Download project source</a>')}${metrics}${publicationLinks()}
<div class="dashboard-grid"><section class="card"><h2>Project Summary</h2><p>This portfolio converts a traditional SAS-style storm analysis workflow into a transparent Python pipeline. A complete sequential code-cell rerun, independent artifact checks, and documented identity safeguards are documented in Validation & QC. It reads SAS and Excel data, prepares analysis-ready datasets, derives storm attributes, joins summary and detail sources, calculates storm-level statistics, and exports reusable Excel/CSV reports and figures.</p><div class="tech-pills"><span class="pill">Python</span><span class="pill">pandas</span><span class="pill">NumPy</span><span class="pill">Matplotlib</span><span class="pill">openpyxl</span><span class="pill">SAS7BDAT</span><span class="pill">Jupyter</span></div></section>
<section class="card"><h3>Portfolio Evidence</h3><div class="stat-list"><div class="stat-row"><span>Data sources</span><strong>SAS + Excel</strong></div><div class="stat-row"><span>Workflow</span><strong>End-to-end</strong></div><div class="stat-row"><span>Outputs</span><strong>CSV + XLSX + PNG</strong></div><div class="stat-row"><span>Primary focus</span><strong>SAS-to-Python</strong></div></div></section></div>
<div class="dashboard-grid"><section class="card"><h2>Featured Visualization</h2><img class="chart-img" src="assets/storms_by_basin_2016.png" alt="Storms by basin in 2016"></section><section class="card"><h3>What this demonstrates</h3><div class="callout">This is practical Python evidence: data ingestion, artifact checks, transformation, grouping, aggregation, joins, visualization, and report export—not simply coursework or syntax familiarity.</div></section></div>`,
pipeline:()=>`${head('WORKFLOW','Data Pipeline','A clean sequence from raw SAS/Excel inputs to analysis-ready data, statistical outputs, and presentation-ready deliverables.')}
<div class="card"><div class="pipeline">
<div class="pipe-step"><div class="step-no">1</div><div><strong>Ingest raw data</strong><p>Load <code>.sas7bdat</code> and Excel sources with pandas while preserving the original source files.</p></div></div>
<div class="pipe-step"><div class="step-no">2</div><div><strong>Inspect & validate</strong><p>Review columns, types, dimensions, and missingness; derive season/basin/name identifiers and audit incomplete and ambiguous join candidates.</p></div></div>
<div class="pipe-step"><div class="step-no">3</div><div><strong>Clean & derive</strong><p>Standardize dates, basin labels, ocean categories, storm duration, coordinate fields, and analytical variables.</p></div></div>
<div class="pipe-step"><div class="step-no">4</div><div><strong>Join & summarize</strong><p>Link damage records to uniquely eligible summary keys with a validated many-to-one merge; group wind observations by season, basin, and name.</p></div></div>
<div class="pipe-step"><div class="step-no">5</div><div><strong>Visualize</strong><p>Create basin-frequency and North Atlantic storm figures with Matplotlib.</p></div></div>
<div class="pipe-step"><div class="step-no">6</div><div><strong>Export reports</strong><p>Write reusable CSV tables and a multi-sheet Excel report for downstream review.</p></div></div>
</div></div>`,
'sas-python':()=>`${head('TRANSLATION','SAS → Python','The project demonstrates how familiar SAS programming concepts translate into modern Python/pandas workflows.')}
<div class="code-pair"><div class="code-box"><span class="label">SAS concept</span>proc sql;<br>select Name, Season, BasinName,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MaxWindMPH, Cost<br>from damage_detail<br>where Cost is not null<br>order by Cost desc;<br>quit;</div><div class="code-box"><span class="label">Python / pandas</span>damage_detail = (<br>&nbsp;&nbsp;&nbsp;&nbsp;damage_detail<br>&nbsp;&nbsp;&nbsp;&nbsp;.loc[lambda d: d["Cost"].notna(),<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;["Name","Season","BasinName",<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"MaxWindMPH","Cost"]]<br>&nbsp;&nbsp;&nbsp;&nbsp;.sort_values("Cost", ascending=False)<br>)</div></div>
<div class="section-grid" style="margin-top:20px"><section class="card"><h3>SAS skills leveraged</h3><p>DATA-step thinking, PROC SQL concepts, BY-group logic, filtering, derived variables, summary statistics, validation, and report generation.</p></section><section class="card"><h3>Python skills demonstrated</h3><p><code>read_sas</code>, <code>read_excel</code>, <code>loc</code>, <code>assign</code>, <code>merge</code>, <code>groupby</code>, <code>agg</code>, sorting, exporting, plotting, and reproducible notebook organization.</p></section></div>`,
analysis:()=>`${head('RESULTS','Analysis & Results','Selected outputs from the cleaned storm datasets and 2016 analysis workflow.')}${metrics}
<div class="section-grid"><section class="card"><h3>Wind statistics</h3><p>Generated 90 average, minimum, and maximum wind summaries by season/basin/name in 2016. Detail Wind units require source verification.</p><div class="table-wrap"><table><thead><tr><th>Storm</th><th>Avg wind</th><th>Min</th><th>Max</th></tr></thead><tbody><tr><td>AERE</td><td>43</td><td>35</td><td>60</td></tr><tr><td>AGATHA</td><td>30</td><td>25</td><td>45</td></tr><tr><td>ALEX</td><td>55</td><td>40</td><td>75</td></tr><tr><td>AMOS</td><td>57</td><td>30</td><td>80</td></tr><tr><td>ANNABELLE</td><td>36</td><td>20</td><td>55</td></tr></tbody></table></div></section>
<section class="card"><h3>Damage-linked analysis</h3><p>Uniquely linked storm characteristics to all 38 damage records for cost-focused analysis.</p><div class="table-wrap"><table><thead><tr><th>Storm</th><th>Season</th><th>Max wind</th><th>Cost</th></tr></thead><tbody><tr><td>KATRINA</td><td>2005</td><td>173</td><td>$161.3B</td></tr><tr><td>HARVEY</td><td>2017</td><td>130</td><td>$125.0B</td></tr><tr><td>MARIA</td><td>2017</td><td>175</td><td>$90.0B</td></tr><tr><td>SANDY</td><td>2012</td><td>115</td><td>$70.9B</td></tr><tr><td>IRMA</td><td>2017</td><td>185</td><td>$50.0B</td></tr></tbody></table></div></section></div>`,
visuals:()=>`${head('VISUAL ANALYTICS','Visualizations','Presentation-ready figures generated programmatically from the analytical datasets.')}
<div class="section-grid"><section class="card"><h3>2016 storms by basin</h3><img class="chart-img" src="assets/storms_by_basin_2016.png" alt="2016 storms by basin"><p>Counts storms across ocean basins to show geographic distribution.</p></section><section class="card"><h3>2016 North Atlantic storms</h3><img class="chart-img" src="assets/2016_north_atlantic_storms.png" alt="2016 North Atlantic storms"><p>Focused view of North Atlantic activity for the selected season.</p></section></div>`,
deliverables:()=>`${head('REPRODUCIBLE OUTPUTS','Project Deliverables','All major artifacts are generated from the Python workflow and organized for review or reuse.','<a class="button" href="python-storm-data-analysis-source.zip" download>Download complete project</a>')}
<div class="section-grid"><section class="card"><h3>Analysis assets</h3><div class="stat-list"><div class="stat-row"><span>Jupyter notebook</span><strong class="status green">Included</strong></div><div class="stat-row"><span>Clean storm summary CSV</span><strong class="status green">Included</strong></div><div class="stat-row"><span>Damage detail CSV</span><strong class="status green">Included</strong></div><div class="stat-row"><span>2016 wind statistics CSV</span><strong class="status green">Included</strong></div></div></section><section class="card"><h3>Reporting assets</h3><div class="stat-list"><div class="stat-row"><span>Excel storm report</span><strong class="status green">Included</strong></div><div class="stat-row"><span>Basin visualization</span><strong class="status green">Included</strong></div><div class="stat-row"><span>North Atlantic visualization</span><strong class="status green">Included</strong></div><div class="stat-row"><span>Requirements file</span><strong class="status green">Included</strong></div></div></section></div>
<div class="card" style="margin-top:20px"><h3>Reproducibility</h3><p>The project keeps raw data, processed datasets, notebook code, output tables, figures, and package requirements in separate folders—making the workflow easy to inspect, rerun, and explain in an interview. Run run_notebook.py in the extracted source project to execute every code cell and regenerate all outputs.</p></div>`,
resume:()=>`${head('CAREER POSITIONING','Resume Highlights','Use this project to substantiate hands-on Python data analysis and SAS-to-Python workflow experience.')}
<section class="card"><h3>Recommended portfolio entry</h3><p class="resume-bullet"><strong>Python Storm Data Analysis Pipeline | Portfolio Project</strong> — Built a reproducible Python/pandas workflow to ingest SAS and Excel data, clean and integrate 3,172 storm-summary records with detailed observations, derive analysis variables, and automate statistical summaries, visualizations, and Excel/CSV reporting.</p><p class="resume-bullet">Translated SAS-style data manipulation and PROC SQL concepts into pandas-based filtering, joins, grouping, aggregation, and reporting workflows.</p><p class="resume-bullet">Produced storm-level wind statistics for 90 storms in 2016 and integrated 38 damage records for cost-focused analysis using pandas, NumPy, Matplotlib, and openpyxl.</p></section>
<div class="section-grid" style="margin-top:20px"><section class="card"><h3>Skills line</h3><div class="callout"><strong>Python:</strong> pandas, NumPy, Matplotlib, Jupyter, openpyxl; SAS/Excel data ingestion; data cleaning, joins, aggregation, visualization, and automated reporting.</div></section><section class="card"><h3>Interview talking point</h3><div class="callout">“I used my SAS programming background to recreate an end-to-end analytical workflow in Python, including SAS dataset ingestion, validation, transformation, joins, summary statistics, visualization, and Excel/CSV output.”</div></section></div>`};
function render(id){document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));main.innerHTML=views[id]();location.hash=id;main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});document.getElementById('sidebar').classList.remove('open');document.getElementById('sidebarOverlay').classList.remove('open')}
nav.addEventListener('click',e=>{const b=e.target.closest('.nav-button');if(b)render(b.dataset.page)});document.getElementById('mobileMenu').onclick=()=>{document.getElementById('sidebar').classList.toggle('open');document.getElementById('sidebarOverlay').classList.toggle('open')};document.getElementById('sidebarOverlay').onclick=()=>{document.getElementById('sidebar').classList.remove('open');document.getElementById('sidebarOverlay').classList.remove('open')};render(location.hash.replace('#','') in views?location.hash.replace('#',''):'overview');
